const channelConfig = {
    "a3-cine": { id: "QTNfQ2luZQ==", name: "A3 Cine", number: 7, keyId: "ZDZmZjg4MWE2ZjA3OTg2YTgwZDZhZDZmMDQxYjU3ZDQ=", key: "YjQwMWM4N2MyYWIxMWExYTQ4OGVlMWM0NzRiMTA5YWU=" },
    "flow-music-xp": { id: "Rmxvd19NdXNpY19YUA==", name: "Flow Music XP", number: 7, keyId: "YjJhYWU0NGE3NDE0NGJlOGIyMTE4ZTIwZDE0MTJiYWI=", key: "OGE3YWU5OTZkMTJkOGQ1ZDU2MzdkMTA0NGY4ZTA4Yjc=" },
    "flow-music-1": { id: "Rmxvd19NdXNpY18x", name: "Flow Music 1", number: 7, keyId: "ZjM0Y2Q3NzA5ZjA5M2QyM2Q0ZGIwMDkxMDdkOTY4NjI=", key: "ZDhhODI5MTM4ZDk3MGI0NWU4NjdjOTczM2EzMWIyZjA=" },
    "flow-music-2": { id: "Rmxvd19NdXNpY18y", name: "Flow Music 2", number: 7, keyId: "NTk2YjU5OTU4MGIzOWFlMmYzYzQxM2Y3ZWFlMzY5MDI=", key: "MmQ3ZTNkNWQzMWY2ODY5MGZkODc3YTExMWY4NGU4ZTM=" },
    "flow-music-3": { id: "Rmxvd19NdXNpY18z", name: "Flow Music 3", number: 7, keyId: "ZTA3OGIxNWVkNzcwZWM3MWY4MDNjMGVjYzQzZGUwMzM=", key: "NzAxMGJjY2RhNTQ0Zjc0ZDFiNDI1YzRjZWJkMDgyZDQ=" },
    "ae-hd": { id: "QUVIRA==", name: "A&E HD", number: 7, keyId: "ZGIxMjAzNTYyN2E0YjNkNzE5OGI3NjFmMzZiNGEyOTA=", key: "ODBjYTc2MWE4NzU5OTJhYzBlNTBiMDg1MWQ1NTYzZmU=" },
    "hola-tv": { id: "SG9sYV9UVg==", name: "¡Hola! TV", number: 7, keyId: "NWQ3NTk0NzdmMGFkMWJkZWYyYzZkZTA5ZTdjMjc1ZmQ=", key: "ODJjYzZlZWExODVlZWNjOTM0ZGY5NWFkZmJiZjlkYmM=" },
    "axn-hd": { id: "QVhOSEQ=", name: "AXN HD", number: 7, keyId: "MDNlNzdiNWJiZjUxMzVhODVkNTg3YzVhZjJmMmY3MzA=", key: "MWRkMWFiMTkzOGE3OTFkMDNmMDllYjg4NDc4YjQ4ODA=" },
    "mtv": { id: "TVRWMDA=", name: "MTV", number: 7, keyId: "MWYwYzA5ZWQ5ZTU4NDFjZjg2N2JhNmViM2NkZmQ2MWQ=", key: "ODAyYzg5YzZiYWU2YTI0NWFhYWZjZjQwYzE5ODZmYzE=" },
    "warner-hd": { id: "V2FybmVySEQ=", name: "Warner Channel HD", number: 7, keyId: "MDY5YmQzZjBiNmMyNzk0NjdlMDg1NDlmMTdiZjViZDA=", key: "NWFmYTdlMzY5YTZkZTEwOTM4MThhODVhZjkxMmE3NzU=" },
    "gen-tv": { id: "R0VOX1RW", name: "GEN", number: 7, keyId: "NDllYjkyNGJhOTk4Y2E3ZmJiYWVlMzBkY2VmMWVjYjQ=", key: "NmUxMzFiMDRiMmU4NzU5OGZiNTg4YWMyMDU2NzM2OTg=" },
    "espn-premium": { id: "Rm94X1Nwb3J0c19QcmVtaXVuX0hE", name: "ESPN Premium", number: 7, keyId: "NGMyMzBkYmM3ZjZhNGJmYTZhZDBhYTczZmY3OTIzNzQ=", key: "NDE4NmE3YzJhMTVmNTkwYTkzOTk4ODZmZWFlYzQyNTc=" },
    "tn": { id: "VG9kb05vdGljaWFz", name: "TN (Todo Noticias)", number: 7, keyId: "N2NlYjFjZDA2MjJjZDdlODhmY2RjOTlmZTNhNTVkZTY=", key: "OTUxNjM3MDkzZDQxYzczODhhMWVmM2Y2MjBjZmVhMjE=" },
    "tyc-sports": { id: "VHlDU3BvcnQ=", name: "TyC Sports", number: 7, keyId: "MmIyMWM4ZmE5YTMyOWNjZTMxMWE0YzRhNGFhOTk2YTE=", key: "Y2MyM2VhMWZiMzI2MjlmOWU0Zjg4YzhkZWVhZTNlNWI=" },
    "a24": { id: "QW1lcmljYTI0", name: "América 24", number: 7, keyId: "M2IxYjAyN2RkMDExYWYyMGZkOTk1NmMxNmRjMDg0ZmI=", key: "NDVmNzVhYWNmMDU1OTNjOWI2OTNmZTQyN2M2N2U1Yjg=" },
    "c5n": { id: "QzVO", name: "C5N", number: 7, keyId: "MDUwZGY1YzZlNzhjNzc0ZTc4YzNlOTllZWY4YTFiMjk=", key: "MGU0MTQxZDZhYjIxYTM2Y2JjNGRhNzc3YWIzMDk2ZDQ=" },
    "ln-mas": { id: "TGFfTmFjaW9u", name: "LN+", number: 7, keyId: "ZjRlYWRlN2JiYzM5YjI1NDAyYWNmYTMwMWJiYWQwNGE=", key: "YTc0ZDFkZjQyMzVhNzQ4NzgzMjdhYThkNTNmZjI4M2M=" },
    "cronica-tv": { id: "Q3JvbmljYVRW", name: "Crónica TV", number: 7, keyId: "NzQ1ZTdhYmNjOTBkNDFhYjcwNmIyYWMyZjQzNzFkYTM=", key: "NTBhY2Q5ZDE5ZDEzNjFjYjRhOGExM2E4NjdiZGMzNTI=" },
    "canal-8-tucuman": { id: "Q2FuYWxfOF9UdWN1bWFu", name: "Canal 8 Tucumán", number: 7, keyId: "Nzc2MGNhYTA1OGI1MWI3Y2NlMTUxYzA1MzlmYTRhOGY=", key: "ZWRkMDg2YzEwMTFlZDJjNTRjYmU4NjlkMGU4ZDkyODk=" },
    "paraguay-tv": { id: "UGFyYWd1YXlfVFY=", name: "Paraguay TV", number: 7, keyId: "NjhhNWJkNmM1OGU2YzA1YmFjZmQxOGQzZmVlYzMxZjI=", key: "YWUyM2Y4MzU3NTEyZGYyZGZhYmNiODEwNGIwNzgxODI=" },
    "paramount-channel": { id: "UGFyYW1vdW50", name: "Paramount Channel", number: 7, keyId: "Yjg1YjcxMGVjZmYzZTM4ZjMxZmM4ZTI0OWIxYzFjZWY=", key: "YTE1NDRjMTkzZGRlNmY4ODU4YzkzNThlZTY5YTYwYTc=" },
    "comedy-central": { id: "Q29tZWR5Q2VudHJhbA", name: "Comedy Central", number: 7, keyId: "NDAxM2Y3ODRjNWVmNDMxOGFkNDcwMjRlNjFlYjA5NGU=", key: "YmFkNDMzYTU0N2Y5N2M3ZjY1Y2RhNWU4M2I4ZGQ0MTY=" },
    "boomerang": { id: "Qm9vbWVyYW5n", name: "Boomerang", number: 7, keyId: "NTc5MmU2MTNmY2ViNjk5Yzc5Y2JjMGU3NWZlNGNkMzc=", key: "YTY3Mjc5MzczMDQ3NmVkMjNlNWMyYmNlMmZmNTcwYzY=" },
    "dreamworks": { id: "RHJlYW13b3Jrcw==", name: "Dreamworks", number: 7, keyId: "N2YzMGM0M2U0NzU0NDQxMjIyMWZkNjQyMDFkOTJmNGI=", key: "ZjgzZDA5ZDc1YTA5NDZiMWQ3MWFhNDhjMjAxYjRkOGI=" },
    "animal-planet": { id: "QW5pbWFsUGxhbmV0", name: "Animal Planet", number: 7, keyId: "NDE0NmE4ZWNiYjA1NDBkYzgwN2M2Mzg5ZWU4N2UwYmM=", key: "MGMzY2RjMWIzZTQ2MTdjNTczNjEyNjVlOWZhNGM1YmQ=" },
    "history-hd": { id: "SGlzdG9yeUhE", name: "History Channel HD", number: 7, keyId: "ZTgyMzE4ZTUxOGJhNzBjZWEzZDdiMzdiZWY5OWU2OTI=", key: "YTA1ZmNiNjM0YzA3MWE1MTRlMzAzOWUxYzI3NGI0ZGI=" },
    "id": { id: "SUQ=", name: "Investigation Discovery", number: 7, keyId: "MDk1NmNhZjJlMmJkNDFmNDlmZGNlYWQ3Y2M5NGZlMjQ=", key: "NjQwYzQ5NTc4MDczYTkxMTkzODYxN2ViNGU2NTJkNmM=" },
    "bravo-tv": { id: "QnJhdm9UVg==", name: "Bravo TV", number: 7, keyId: "YWQ3ZmJiZWMzOWNlYTRhNWE2M2FjMTNkOTRkYTQ4ZDQ=", key: "ZjcxMDg3YjRkYzIxMWRiMDc5MjM3YzBmYjc4M2ViOTM=" },
    "sony-channel-hd": { id: "U29ueUhE", name: "Sony Channel HD", number: 7, keyId: "ZmQ5NjE5ZjlkN2MyZDUxMTVhMzM5OTQxMjc5ZTBiNGI=", key: "YmY1NTYzNWU2NTkxZjkwNTY1OWZhMjdhYjNjYTI4MTI=" },
    "trutv": { id: "VHJ1VFY=", name: "TruTV", number: 7, keyId: "N2QwY2VjZmZlOWMyOTczNDM0M2NmOTk4Mzk3OGMxYTE=", key: "Zjg2YjVhYzA1ZjJhMjYyNmI2YzYxYmQ0ZTEzMzQ0ZDg=" },
    "hbo-pop": { id: "SEJPX1BPUA==", name: "HBO Pop", number: 7, keyId: "ZjRlMWNlNWNlZjdlOWExMTBmZTk2OGY4ODgxYjIxZmE=", key: "NmJiZTIwNjJiMTUwYjExNDk2Y2RkNWZiZGQ5Yzg5ZDY=" },
    "discovery-turbo": { id: "RGlzY292ZXJ5VHVyYm8=", name: "Discovery Turbo", number: 7, keyId: "YTYxMWRkYmY4YzE1ZmE2MTdhMGMzOTFjYjdiM2UxMjg=", key: "MGNkMTMwMGJhZjg4OTAzODBmZDQxMTI0OTYyMTk1YzQ=" },
    "disney-jr": { id: "RGlzbmV5SnI=", name: "Disney Junior", number: 7, keyId: "YmQyOWM0YTUzOGYyODg0NWNlMzM1ODExMTE3NDk0Mjg=", key: "NDZkOTU4OWY0MWExMWMzNjM3YzA3YzYwNDk1NmRlYWM=" },
    "ip": { id: "SW52ZXN0aWdhY2lvbl9QZXJpb2Rpc3RpY2E=", name: "IP", number: 7, keyId: "NTI5OWY5NmY4NzNhYTBmMCU0N2VkYzRlMTU3ODQ3MTc=", key: "OWQ1MzE3NmIwOTY5NDkyZjJkOTNmMTg2N2JlMWRjZTE=" },
    "espn7-uy": { id: "Rm94U3BvcnRzMl9VWQ==", name: "ESPN 7 (UY)", number: 7, keyId: "NWZjN2I2NjJlNjljMGZiZjhkMzk2OTExNjZiMWM5MTk=", key: "ODkxNTdjZGQyNWRmMjVkNTZmMWVjY2NlZTM4NTA4ODg=" },
    "espn4": { id: "RVNQTjQ=", name: "ESPN 4", number: 7, keyId: "MjRmMmIzZTc0MWYwZDllOWE4ZDUxNmZhZmYzOGJkZGM=", key: "YmJkM2ZkMDJmYjEwNGUxNDYzYWM1MjhhMTNmNjdlNGE=" },
    "espn6-uy": { id: "Rm94U3BvcnRzM19VWQ==", name: "ESPN 6 (UY)", number: 7, keyId: "NWZjN2I2NjJlNjljMGZiZjhkMzk2OTExNjZiMWM5MTk=", key: "ODkxNTdjZGQyNWRmMjVkNTZmMWVjY2NlZTM4NTA4ODg=" },
    "eventos-hd-uy": { id: "RXZlbnRvc19IRF9VeQ==", name: "Eventos HD (UY)", number: 7, keyId: "NDhkMGUzNGM4Nzk3YzVjMmE3NDJkMjYzMGE4ZmI5NzU=", key: "ZmI1ZDEyYjlkOGZlYmU4MzZlNTY3MGFiZDAwM2RkY2E=" },
    "telemundo": { id: "VGVsZW11bmRvX0hE", name: "Telemundo", number: 7, keyId: "NTNkNzUyZTQ2NDlkYWRkODA4ZDkxMzk4NWY4NmVlNzc=", key: "ZDFmZDI0ZGIxYjYxZDYzNGNhYmZjNDQ1MzhjZTliMGU=" },
    "espn3-uy-py": { id: "RVNQTjNfVXktUHk=", name: "ESPN 3 (UY-PY)", number: 7, keyId: "ZWQ1Mzg3MWRjNTBkY2RjNTlhNjI3MWRiM2M4YzUxYjM=", key: "MGMyMWRjODYyOWUzZjJlNmZlOWVmYThiODBkYzQ0N2U=" },
    "a3-series": { id: "QTNfU2VyaWVz", name: "A3Series", number: 7, keyId: "NWUzNGUwOGFlNWFlNDQwZjAxYTAzZTUwNWRkMjRhNTc=", key: "ZWQzMGNjN2Y1MDQwYTc1ZDczZjYxOTMyMDI0OTI3MmI=" },
    "espn2": { id: "RVNQTjJfQXJn", name: "ESPN 2", number: 6, keyId: "NjVhNWJmYTNjN2E3MmRkZTYwYmU5YjBjNzQwNmM4ZmM=", key: "MGI0MGFlOWY3OGE3YmFjM2I1N2VjYmY3MmQzYzA4MWU=" },
    "cinemax": { id: "Q2luZW1heA==", name: "Cinemax", number: 6, keyId: "OTc3OTI4YTkyYjgyYmEzNzgxNzQxYTY0NzBmOGY0NWI=", key: "NTFmNGU2MjgyN2MxMjhmNzIxMGI3OWExMTU4NzY2MWE=" },
    "eventos-2-hd": { id: "RXZlbnRvc18yX0hE", name: "Eventos 2 HD", number: 6, keyId: "ZTU0ZTllYTg3YTYzNDY1OGZiYmEwZTM4MGFhNzAxYTc=", key: "NGU0ODZkMjVkN2QwZTdkMTMxNzQzYjI4NTk2M2M2NDM=" },
    "canal-8-cordoba": { id: "Q2FuYWxfOF9DQkE", name: "Canal 8 Córdoba", number: 6, keyId: "MTAzY2UyMTRiNGQwNGM4ZWI0ZGQ0MzY3MGU5NTZkYWQ=", key: "MjBlMDMwNTc2YjhkYzRkZjBkMWM2OGUxNmFmM2JjMGY=" },
    "canal-26-hd": { id: "MjZfVFZfSEQ", name: "Canal 26 HD", number: 6, keyId: "ZTMyYWFhNGI2NzQzMGIzYjUxYmUxZWZjZTVhNzRhYzU=", key: "YWQ2MGM1ZTFkMzc4YTk3MjcxYmY4Njg4ZjA5NGQwOTI=" },
    "diputados-tv": { id: "RGlwdXRhZG9zX1RW", name: "DTV (Diputados TV)", number: 6, keyId: "OTY2NmIxOTUxNzE0NDJhZmQ0NTUxYThkZTAxMjkxYTY=", key: "MWMwMDYxZGY5YjRiMDk4ZTQwMzU1MTY3ZTk3Y2ZiZjA=" },
    "argentinisima": { id: "QXJnZW50aW5pc2ltYQ", name: "Argentinísima Satelital", number: 6, keyId: "YTYyNDNmNDYzNjY0NDVlYmJmMzExN2VjMjczNjU0ODE=", key: "ODE2NjdjZGMzYmNmMTlhNmE2NmMwOTE5ZmEwMGEyMGI=" },
    "metro": { id: "TWV0cm8=", name: "Metro", number: 6, keyId: "NzE5YWEzYTVlMjcwYzdmNjllYmEzNzRlZDgwZDc5ODY=", key: "OTdhYzU5MTE4Y2Y0Y2YyNDJlMmMzMWU4N2NkMzhlMWU=" },
    "bbc-world-news": { id: "QkJDX1dvcmxkX05ld3M", name: "BBC World News", number: 6, keyId: "MDE5ZjcyZjIwOTFkNGNiZWE1OWZmOGM4NWIxMTdmODY=", key: "YTRlYWM1MTE5NTUwNjc1MmY5ZjYzYWQyNGRlZjljMzc=" },
    "film-arts": { id: "VGhlYXRlcl9IRA==", name: "Film & Arts", number: 6, keyId: "NTI3OWMwNWVhNTFjNGRhZThlN2ZhNmJlODg0NDgwODk=", key: "YjI4ZGZhZmJhNGI4NDhkZmQ1ZDdjMTc3ZWJmMTkxMDg=" },
    "glitz": { id: "R2xpdHo=", name: "Glitz", number: 6, keyId: "ZjgxMmVmODFkNmNlNDI1YThkYjQwMTJhMWVmOGIwYzE=", key: "NWMyYjk3OTFiMTA3NDcyN2ViMzQ5NTg4ZTMyYmRjMGE=" },
    "quiero-musica": { id: "UXVpZXJvX0hE", name: "Quiero Música", number: 6, keyId: "YTM1NGIwYzgyYTNhNzIwYzRhNmY1MmVkNWExMTkwZjQ=", key: "NDVhNzZkY2M4NGYwNThjZmFiYzhiOTU4ZDczMDNiMjg=" },
    "discovery-world-hd": { id: "RGlzY292ZXJ5X1dvcmxkX0hE", name: "Discovery World HD", number: 6, keyId: "MzRlZTk0YzIyNjMzNDVmN2EzYTU5MDY2MTI2NGU0OTA=", key: "NTY3NTdkNjU2YTY5N2FiN2EyZTVlMDgzYjVkMjFiYjU=" },
    "eurochannel": { id: "RXVyb2NoYW5uZWw=", name: "Eurochannel", number: 6, keyId: "NmYwZmMyMTRkOTg0NGE3NTkwZjA4ODRkNTViNDRjNDI=", key: "YjJmZTFiYjVmOWM3OTAzNTMwMWMzMjhjMWU5M2IwZWU=" },
    "discovery-science": { id: "RGlzY292ZXJ5X1NjaWVuY2U=", name: "Discovery Science", number: 6, keyId: "NDZiYTQwOWZiMDRlNDBmYjg2YjQ2NmQ5N2UzYTk1ODg=", key: "ZjEyOWZiOWI1ZDIxM2UyMGUyYWJlNTI5YjhjZjI1OTc=" },
    "cine-ar": { id: "SU5DQUFfVHY=", name: "CINE.AR", number: 6, keyId: "ZDQ0ZjQwZTQ5ZDI5NDVjMWEzNzAxYzA4ODVmZjBiMDA=", key: "NjM4MmI2Mjc5MDg3NDAyNzE0YjY4MjQ2ODhjNDU2ZGY=" },
    "tv5-monde": { id: "VFY1X01vbmRl", name: "TV5 Monde", number: 6, keyId: "NjIwMzRmZjU5ODhiNDc4N2IxN2NkZjZmNzUxYTMxNDI=", key: "YjM5MzhmMGFmMjhiNGMwYzA4MmIwZDQyMTBlMzg5YTA=" },
    "mtv-hits": { id: "TVRWX0hpdHM=", name: "MTV Hits", number: 6, keyId: "NjEwMDhkZmM4Njc1NDRjZDg3MmRlOTliMWYyYjgyY2Y=", key: "NzE2NDQ5NzU2MzE2YjkxYzU0ODAzYWFhMjJhMmZiZjA=" },
    "mtv-hd": { id: "TVRWX0hE", name: "MTV HD", number: 6, keyId: "MGM5ZWIzZWFkMzhhMTIyYWM0NjBhZDk2YThlYmZkMmU=", key: "NjZiZmJmYTQ0NDllYjhiYzFiY2Y3NTc3ZDViZmZhYWQ=" },
    "nick-jr": { id: "Tmlja19Kcg==", name: "Nick Jr.", number: 6, keyId: "ZTgyNGIyMjc3YTg2ZmQ2YWRmYzQwYWE5NDhlNTA2NGE=", key: "MjhkYTJkYmJlOGUxYTE0NjNiYmIyMzg5NWI5MjIwODM=" },
    "tve": { id: "VFZfRXNwYW5h", name: "TVE", number: 6, keyId: "NTNlMGEzNzQxZTJlNGZmNTg0M2YxNjViNTMzMDkwODg=", key: "NDUwOTVjYWFiZDlhMzU5Y2Q3ZWEzOTEwZDg2NWQ2NDM=" },
    "wobi": { id: "V09CSQ==", name: "WOBI", number: 6, keyId: "ZjJlNDRhNzE5OTQ3ZWJmZTM3ZGU1MjdhOWQ2ZGY3MWU=", key: "MDI5YmRkZWIwODkwOWRkNjZhODAyNzZmYzMzOGQ2OTI=" },
    "volver": { id: "Vm9sdmVy", name: "Volver", number: 6, keyId: "MTk0ZTUzMTg0YTQyNGNlMjk4OWFkODJjNWYyOGZiYzU=", key: "NjVkNjBjNWNjNGRlMDMxMTcyYmUwYTZhNTFlZGJkZmU=" },
    "telesur": { id: "VGVsZXN1cg==", name: "teleSUR", number: 6, keyId: "NTIzNWQ4ZWUyOWYxNGNlNmIyNmVhNWQ4MjhhZWU3N2E=", key: "NmJmNmJkMzM5ZTMwOThiYWJjMmFiMGI5ODRjZDIzNzY=" },
    "lifetime": { id: "TGlmZXRpbWU=", name: "Lifetime", number: 6, keyId: "ZWFlNTFiMWQ2N2ZmNDdhZGFjN2I2YmQzYTRiMTEyMGE=", key: "YjRkNmJiNDcxOTNmMzNmZmMxMjM3OWNkYzQ0NzQ1NWQ=" },
    "antena3": { id: "QW50ZW5hXzM=", name: "Antena 3", number: 6, keyId: "MWUxYWQ0MjJhNjcxNDQ4MmI2NmZhNzAyYzE2ZTUwYzY=", key: "NGZkZjI4YTBhYjkxMzU2Y2E1NWE3NWY0ZTliZjhjOTI=" },
    "fox-news": { id: "Rm94X05ld3M=", name: "Fox News", number: 6, keyId: "M2ZlM2YzMWE1ZTdiNDhhMWI1NDhlOTM2NDc1N2NlNjY=", key: "MzI5OTNmYzI4MTIwN2ZlOTE1ZjZmMWU5OTA5NTc4Njg=" },
    "tv-chile": { id: "VHZfQ2hpbGU=", name: "TV Chile", number: 6, keyId: "YzVkMGQ3NmUyNDg0NDIzNTk4OGY5MjY1NjE5ZTVmZWM=", key: "NDQ2YjcxYTZkZWI4MDZjNmYxMjllMjVkZTk5OWQwN2M=" },
    "mas-chic": { id: "TWFzX0NoaWM=", name: "Más Chic", number: 6, keyId: "ZGFjOGZmMTY4ODk5NGVmZDg5ODIyMmFjZGQwNWNhZmM=", key: "MjJmZGY5N2M3MjMzNjY3NTE4MjU4ZWQxNmNjYjI1NDU=" },
    "studio-universal": { id: "U3R1ZGlvX1VuaXZlcnNhbA==", name: "Studio Universal", number: 6, keyId: "ZDliNTQxZTNjZDA2NGQ1Njk4NDNkYTQyNzg4ZDQyNjM=", key: "YmJhNWQyNmFkNTA1MWZiM2YyY2Y3ZTNkZDhhNGE3ZDg=" },
    "isat": { id: "SVNBVA==", name: "I.Sat", number: 6, keyId: "ZGI3NjQxNjQ5MzRhNDg3NDlhN2EwMWJkMDE1Njk0ZjM=", key: "NTEyZjNjODg2OWFmNDVlNmU1ZGQxNTI1YjZhNzc4Njc=" },
    "sun-channel": { id: "U3VuX0NoYW5uZWw=", name: "Sun Channel", number: 6, keyId: "MTU4MTc3NjkyYWEzNDYzZWFlNWY0ZTFmNzI0MDNlOWM=", key: "MWM2YzAyNmZiYTljZjdlY2I1NzZjN2JlZGNlMGVhZDQ=" },
    "rai-italia": { id: "UkFJ", name: "Rai Italia", number: 6, keyId: "ZDIxNDU0N2Q3ZDlhNDAxMWEzOWE4OTljZTZlNzAwNzE=", key: "MTZjMmVkMDYxN2NmMWUxMjNmM2FmNmVhODg3NWE4MmQ=" },
    "venus": { id: "VmVudXM=", name: "Venus", number: 6, keyId: "MzQyMzdkMmFlNjY4NGVlN2EwMTFmNWI5YzdjNDNlNmQ=", key: "MDVkOTczZDk4NzkxNTEyMGU1Njc4ODBmNTBhNDIyYWY=" },
    "sextreme": { id: "U2V4dHJlbWU", name: "Sextreme", number: 6, keyId: "OTViZDY0MjI3YWNmNDU4ZGFmNzg4NmY4MDNkMDI5OGU=", key: "NzllMjhlZTBlYzU4OTU4YmI2NjZmOWU1M2EwY2Q0MzQ=" },
    "playboy-tv": { id: "UGxheWJveQ", name: "Playboy TV", number: 6, keyId: "ODU3N2Q4MWVhZjMzNDM2ZDlmMWU0ODIzNjA2ODVhN2M=", key: "ZjYwOGEwYWM3MDNjZmFhZjk0NDI1NzRkOWEyYjg3ZmI=" },
    "tnt-sports": { id: "VE5UX1Nwb3J0c19IRA", name: "TNT Sports", number: 6, keyId: "YmM4MGZhM2RhNjk2ZTUwM2Y5NDBmZGU1ZjY4MWExYzU=", key: "ZWE0NmU0ZTlmMTEzMmU4ZGQ3MWZiNzdmN2Q1NTA1OGE=" },
    "tv-publica": { id: "Q2FuYWw3", name: "TV Pública", number: 6, keyId: "Y2M4YzgyYWMyZWM3ZTk3OTk1MjdjMjlkYjczNTRlODE=", key: "Y2M0YWFlMTczZGQyZWYxN2FlMjZiZTNmN2FlODc2NjI=" },
    "encuentro": { id: "RW5jdWVudHJv", name: "Encuentro", number: 6, keyId: "YWMzYWU3OGJlYjY0NDc4YWIzOTBiNGFkNzA3M2UwYzk=", key: "YzdkNjY5NzYxYzM1MTZkODUyYTBlZGY5ZTA3YzkxOTg=" },
    "telemax": { id: "VGVsZW1heA", name: "Telemax", number: 6, keyId: "ZTdlYzM2NGFkNjg1NGZlZGFkNzk3NTM4Y2I1ODc4MGQ=", key: "NTdkZmIzZmNhMmNhMzViMzdmZjgxYzM1NTk1ZTliZTg=" },
    "net-tv": { id: "TmV0X1RW", name: "Net TV", number: 6, keyId: "ODlkNDMzMTY2ZWRkMzFkNTZkZjJhNTlkZjhlYzY3MDQ=", key: "YjIwMTVmYWRlZDBhNDU2ZDEwYWE4ZGIxYjRjYmFjNjg=" },
    "el-doce-cordoba": { id: "Q2FuYWxfMTJfQ0JB", name: "El Doce (Córdoba)", number: 6, keyId: "OTA0MjI2NDBkM2U4NDYxNTlmYTQ1MGY4Mzg3MGVkNGE=", key: "YWJiM2NkOTRhZWNlMWE0NjJkZjI1YThmMjEwODVjY2E=" },
    "el-garage-tv": { id: "RWxfR2FyYWdl", name: "El Garage TV", number: 6, keyId: "MDNkMWRmYjhkZjAzNGQ4YjgxZTU3NzUzZGYwMGEzNmQ=", key: "MDhkODM2NjBkYjRhNzNiYjFkNjFkNjBiMDlkZjVmNGQ=" },
    "universal-tv": { id: "VW5pdmVyc2FsX0NoYW5uZWxfSEQ=", name: "Universal TV", number: 6, keyId: "NmNmOWExM2Q2ZmQ2NWEwZjJlMWNlZTM5NjlhYWI5ZjU=", key: "ZWE2MWMzYzFhZGVlNzFiNWMyZTk3NDRlNDFkNGI3NWY=" },
    "europa-europa": { id: "RXVyb3BhX0V1cm9wYQ", name: "Europa Europa", number: 6, keyId: "YjQ3ZjI1N2RmMDMxNGQwOWE3ZjgzNTVjM2FiZTFkYzY=", key: "YmRjOWYxNjk2YTgyZWU3Mzk4ZGQzYTdmYTgyMzAwZTI=" },
    "euronews": { id: "RXVyb25ld3M=", name: "Euronews", number: 6, keyId: "ZDg2YjBmNTZkMzJmNDVhZGIwYTZiNGU0ODhjOGYwYzI=", key: "ZTRmMTgwYjBlNjFiZTNlODBhYjYwMmRmNWU1NmZmM2Y=" },
    "food-network": { id: "Rm9vZF9OZXR3b3Jr", name: "Food Network", number: 6, keyId: "NmNhMGZiYWQyMWEwZTkwOGMwMjgwZGNjMjdlNmVlMGU=", key: "NjI2NzBlZWRiYWZkZjkzNjBiNGVjYWVkNzM4ZTI2Y2Q=" },
    "e-entertainment": { id: "RV9FbnRlcnRhaW5tZW50X1RlbGV2aXNpb24=", name: "E!", number: 6, keyId: "NTg4MzU1MzIwN2YxM2UzZGM4Y2VjZDExMTNkNWJhNjg=", key: "NDU0MzRkNDA2MzZkZmEwZTUzMTJiOTMyMThlMDIxODU=" },
    "cm-musica": { id: "Q00=", name: "CM (Canal de la Música)", number: 6, keyId: "NjgyZjM2YjU3MzZmNDU2MDk1MWNhMTRiODBkMjk1MjQ=", key: "M2FjY2I3MjkwNjdhMzliM2I4MTQzZjFiNDQ3YjlkMjU=" },
    "pakapaka": { id: "UEFLQV9QQUtB", name: "Pakapaka", number: 6, keyId: "MzM0MDAxYjJmMjY0NGRmOWJkZjM1ZTkyZDJiODlmOGY=", key: "NDc1ZWM4N2Q4NmVkMDYzNmRiYjZkNmQ5ZDRhNDNiYjc=" },
    "history-2": { id: "SGlzdG9yeV8y", name: "History 2", number: 6, keyId: "ZWNiZTk3ZWMzNDc4NDMwNGIzOTBhMTJiYTM4NTRjY2Y=", key: "NWEwZWUzNmVkOWI4OTIwY2IxOTU0NmZkOTJmMmQ0MTU=" },
    "syfy": { id: "U3lGeQ==", name: "SYFY", number: 6, keyId: "OWNkOTljYmI0NjZjNDJlNWIzM2U3YTJlZjdlMmM3ZGY=", key: "MThkOWZhY2NkYWYyZDE1ODA3ZDBhM2Y3MTNlOGIyYTQ=" },
    "tbs": { id: "VEJT", name: "TBS", number: 6, keyId: "NDlhMDE3OWIwMzRhZTg5OWNiNjdkOGE1ODM0MTgxYWE=", key: "NDg2ZTJjNmQ2OWFkZWE3ZTE3ZjI5NjBlOGUzNjY2MTI=" },
    "tcm": { id: "VENN", name: "TCM", number: 6, keyId: "YTVmNDRhNWUzMDcxNGNmM2JjZWU3YzdmMTVhMDhiNGU=", key: "YzNjMTQxYWU5NDFhYjk3NTAzMzljM2FmNDVhNjVjZTI=" },
    "hbo-2": { id: "SEJPXzI=", name: "HBO 2", number: 6, keyId: "YzkwY2M1N2FkMmM0MzZlNWE3N2RiMmY4ZDlkYjJkODU=", key: "MDRmNmM3Mzk4NGJkY2ZmZDAxMzA1MDYwODQ5NzkzNWQ=" },
    "hbo-plus": { id: "SEJPX1BsdXM=", name: "HBO Plus", number: 6, keyId: "ZjBlN2Y3ZDQ1ODk5MGVkZmFiN2I5OGI0MTI1NjQ2MTU=", key: "NzkyMDU3NTRiN2Y4NGE2MjY2MWMyZGJlOWRlNWRkNWQ=" },
    "hbo-family": { id: "SEJPX0ZhbWlseQ==", name: "HBO Family", number: 6, keyId: "NTM1NDczMTMyZjY4MDgyMTYwYjQ4OTQ4MmNhMzVmOGU=", key: "ZTkwZmQ5MWZjZDNmYzgwOWJlZDJiMWMwZDM3ZjcyOTc=" },
    "hbo-xtreme": { id: "SEJPX0V4dHJlbWU=", name: "HBO Xtreme", number: 6, keyId: "ZDUwNDAxMWJiZWY0NjdjMGRlM2E3NTM0ZTMwMmE2ZDQ=", key: "MzM0MTAzZTJhYmUxNmZhYTdmOWFiMmUzMDk3YzVhNTg=" },
    "hbo-mundi": { id: "SEJPX011bmRp", name: "HBO Mundi", number: 6, keyId: "NzgyMWIyNjYyMTQ4ZmUzMzNkNTE5MWFjYmI4YTVjMWY=", key: "YWU0M2YzZTI1NDUyMzdlYmRhNThiMTM4MTNiNWQzMjg=" },
    "hbo-signature": { id: "SEJPX1NpZ25hdHVyZQ==", name: "HBO Signature", number: 6, keyId: "ZTg2NjQ5OWZiYzExNDlmNDk5ODk2NzIwNzVhYTNhNjg=", key: "ZDJkZDVjOTU2MjNjNjM0MzI0MDk4MWMyMjAyZmMzMTE=" },
    "tlc": { id: "VExD", name: "TLC", number: 6, keyId: "NTg3NjFjN2IyODE5NDkxZWIzYTBkNzY1ODQyYzM0MWE=", key: "OWRhYmM0OGY4OGJkN2YyNjY3MzRlNTc1MDFiZDZmNDc=" },
    "canal-de-la-ciudad": { id: "Q2FuYWxfZGVfbGFfY2l1ZGFk", name: "Canal de la Ciudad", number: 6, keyId: "NWVlNzgzMmIzY2YyNGQxZGJhMDg4MzY1ZmE1ZDA1NDM=", key: "NjljZWMwMDY0MDk4MjNjMDZmYmYyODY2YTIzMWI0Zjc=" },
    "discovery-kids": { id: "RGlzY292ZXJ5X0tpZHM=", name: "Discovery Kids", number: 6, keyId: "ZmZiMmYwZjYzYzIzYTM1OTJkNDY1M2U5MzhiOWNhMTk=", key: "ZDM2NjFhZTg4MWZjNTVmYzdhMTU4MTVjZDQzOTc0N2I=" },
    "htv": { id: "SFRW", name: "HTV", number: 6, keyId: "ZGFlY2VmNWZlMzJmNGNlMDgzYzZhMGM2OTI3NTVkNmE=", key: "ZDQyMjdmMjQzODlhOWJhNzcyOTMyMTRiOTNlYjBkN2Q=" },
    "nba-tv": { id: "TkJBX1RW", name: "NBA TV", number: 6, keyId: "ZDBjMzhkZTNjOTg0NGU0ZTlmOTc1ZGZmYjNlZmY4YWQ=", key: "MTQxY2EwZmRmNmViYWRmYTcxMDc1NzZiOGUwOWUxMTc=" },
    "universal-cinema": { id: "VW5pdmVyc2FsX0NpbmVtYQ==", name: "Universal Cinema", number: 6, keyId: "ZjZhZTJlMTcxNzMwNTVlNGNhNjlkYzE4OTYzNDA2YWU=", key: "NWE5NTVjMjllYjg4YTBiNGM5YTI1MzhjYzRiM2FlYTI=" },
    "universal-comedy": { id: "VW5pdmVyc2FsX0NvbWVkeQ==", name: "Universal Comedy", number: 6, keyId: "MDYyYzVkMjUxMDVhM2E5MzViNjdlMzY5MjNjNzNmMjg=", key: "ODhjMmQ0Y2VjNDIwZjE4ZDI0NzcxNTJjNjZjNzg3MGQ=" },
    "universal-crime": { id: "dW5pdmVyc2FsX0NyaW1l", name: "Universal Crime", number: 6, keyId: "MWVmZDdlZGY2MGUxNTE0Zjc3NWRkMTNkMDQ2YWU3MDg=", key: "YzJlZjFhYmJkOTQ1YzYyYzExYjEzNzVlYWFhNTBmMGQ=" },
    "universal-premiere": { id: "VW5pdmVyc2FsX1ByZW1pZXJl", name: "Universal Premiere", number: 6, keyId: "MGViMjBiNTFhZDEzYjU4YWQ0MTdmMTEzMThlNTg4YjM=", key: "YWQ1ZDI5YTMzZDczZDIxMTg3MTU3ODAyZGU4ZTYwOTc=" },
    "universal-reality": { id: "VW5pdmVyc2FsX1JlYWxpdHk=", name: "Universal Reality", number: 6, keyId: "Y2VkZDljMWE1YzJhZTQzZjgwZWUzMTk3MjEyMDE2ZDY=", key: "YmY0N2EzYzM5ZTE2NGE5N2VhNmFkYzRjOGRkNTc0MzU=" },
    "las-estrellas": { id: "Q2FuYWxfZGVfbGFzX2VzdHJlbGxhcw==", name: "Las Estrellas", number: 6, keyId: "YjM3ZDg1YmU5ZDJiNGI2MTlmOTQ1YmVmZjcxM2ZkYTM=", key: "OTE3MzA5Yzk4ZjA3MmIwYmQ0ODRkZDY1NjBjNmQxNjY=" },
    "canal-rural": { id: "Q2FuYWxfUnVyYWw=", name: "Canal Rural", number: 6, keyId: "YjAyYzU2ODE2M2MxNGNmZGE0ZGRiOTU4YTBhYWI3NDI=", key: "ZWY2NGE3MGFjODVhNjYzYTMzMDhiZTY0NzY2MTBhYWQ=" },
    "kzo": { id: "S1pP", name: "KZO", number: 6, keyId: "Njk1ZDA3OTg4MTE0ZjdmZWMzMWY4ZjI3YTZkNmZjMzI=", key: "OGU0ZmJiOTZjZmY2YTMxYzg4ZjgxNTY1YjE5OWExM2E=" },
    "golden": { id: "R29sZGVu", name: "Golden", number: 6, keyId: "YjdkMDg1ZGJkNDUzOWFmY2M2YTU1NDQ1ZWZiMmIwNGU=", key: "MGE1NWZiZTA0NGZlZDM3OWQxNjMyYjU4OTI2NWI1NzE=" },
    "c9n": { id: "QzlOX0M0", name: "C9N", number: 5, keyId: "NjQ2NzAwZWViMTRjYWRmYTA1NDNhMjBjZjQxM2QzN2U=", key: "NGZjMDM3YzQ2MjAyMzc2NDYyNGQ4NDQ2NDQyY2JiY2E=" },
    "discovery-h-h": { id: "RGlzY292ZXJ5SG9tZUhlYWx0aEhE", name: "Discovery Home & Health", number: 4, keyId: "OWIwYTc2ZGQ3YTBkZjFlMWI0MzIwYWViMTI1NGQxYTk=", key: "ZDAxMTI2Nzc3NWMzOGQ2ZDJhYjA5YjQyOGMwM2Q2M2Y=" },
    "natgeo": { id: "TmF0R2VvSEQ=", name: "National Geographic", number: 3, keyId: "NGJlMGM2MWNlZGRjNjIyOTRjYzllMjNiNjI3YWY1M2Q=", key: "ODUyYzE5MzVkMTFjM2M1M2QwYTFjZWZmM2JiM2JmMTY=" },
    "tnt": { id: "VE5UX0hEX0FyZw==", name: "TNT", number: 3, keyId: "ZmFhZDE3MjJhNTc1ZjRkOWVjN2I3NzRkYjYzYzg3OWM=", key: "Y2YwMTg0ODMwMzQ0YmEzNmFkMmZmZWY5ZGQyZGQ5ZDA=" },
    "tnt-series": { id: "VE5UU2VyaWVz", name: "TNT Series", number: 3, keyId: "NWMxNGQ2YWViMTliZjExM2VkZjkxYTdiNTQ0MjUzY2I=", key: "OGQ3NzZkNmY5YzVjODQwZWJlODhkNzY3ZGQ3MzE2OTI=" },
    "cartoon-network": { id: "Q2FydG9vbk5ldHdvcms=", name: "Cartoon Network", number: 3, keyId: "ZDdkZjU2ZWZhYTM2YTcxMTQxZDIzODg1NGNjNDZkMWQ=", key: "OGFiYjJlZTkxNTBkOGIyYWY4ZWJlYzBkZTBmODMzYzg=" },
    "nickelodeon": { id: "Tmlja2Vsb2Rlb24=", name: "Nickelodeon", number: 3, keyId: "NjFjMThjZWZlY2MyZDA2N2JlYWE5ZmYxODEzMDUzNDU=", key: "MzhkNmY2NTBjYmY5YTM4ZmQ5ZjM1YzAxZjk4ZTY0N2E=" },
    "adult-swim": { id: "QWR1bHRfU3dpbQ==", name: "Adult Swim", number: 3, keyId: "OWJlMTQzMmUxZTU5NGM4ZDA2NDhhNDRkM2Q5ZjBjNDY=", key: "OGU2Yzc4NWIxNGQ5NzNjNTA0MDc0YjE5MjBmMTFiMTU=" },
    "eventos-hd": { id: "RXZlbnRvczFIRA", name: "Eventos HD", number: 3, keyId: "NWM4NmUyMzczMTdjMjIzMWFjMWJjMTMwZTk5NWZhZDY=", key: "ZGNhY2Y3YjIzOWVlMDNkZjNjNjljYTExZGJjZGU0ZWI=" },
    "tyc-sports-int": { id: "VHlDX0ludGVybmFjaW9uYWw=", name: "TyC Sports Internacional", number: 3, keyId: "NThlMWViZTc1ZDk0NGY2YTk4ZWE2N2IxYzdjMGE1NzI=", key: "MWMzMTFiMDY5ZGJjZTMxY2U4ZTYyYTZlN2UyNDMzZWI=" },
    "telefe-rosario": { id: "Q2FuYWxfNV9Sb3Nhcmlv", name: "Telefe Rosario", number: 4, keyId: "YzYxYjVhYzhlMTY2NGJmNWI1NDRlOTJlYTI1OTdlMWM=", key: "OTM4NDM3YWMyNWYwYTE4ZTA0ZWZjMWEwODM0ODllZGM=" },
    "telefuturo": { id: "VEVMRUZVVFVST19DNA==", name: "Telefuturo", number: 4, keyId: "NWQyNzMxY2Y4YTU5YjczNDM4ZWY1OWQ4OGNkODgyYmY=", key: "M2Y0MTJmYTYzNjhiN2RiNDkwMzU4OGRlNjk1Mzc3ZTE=" },
    "telefe-neuquen": { id: "VGVsZWZlX05ldXF1ZW4=", name: "Telefe Neuquén", number: 4, keyId: "NTU4MjhiNzI4YjhhZmZlNmQxZDU3ZDA1MDAyNTY0NWQ=", key: "OGFjMTFlZDZkMGNjYWVhYzNmODIxODQxOWY2NWJiOTQ=" },
    "telefe-salta": { id: "VGVsZWZlX1NhbHRh", name: "Telefe Salta", number: 4, keyId: "NmM3YTVkZTM5MmY4NzQzMDhlNGRkOGYyODM3ZjExMTU=", key: "OWNjZjllYzY5MjJjNDAzZDY3ZDBkZjc5NTI1NDc1ODE=" },
    "snt": { id: "U05UX0M0", name: "SNT", number: 4, keyId: "OWY2MWRjY2U4NzFjYzQxYWViMjA2ZDA1MDI4ZmMzMGE=", key: "OWY2MjQ4MTk0YTNiZjVlMzViOTZiMTk0ZTg2MjQ2OTM=" },
    "paravision": { id: "UEFSQVZJU0lPTl9DNA==", name: "Paravisión", number: 4, keyId: "YmQ4ZThjOWIzMmVmMDI3ZThmZjRmZjBjZmNlODU1YTQ=", key: "MjkxOGU5ODkzYjU3MGMzZmExZjIxNWI1MmExMmNjOTE=" },
    "npy": { id: "Tk9USUNJQVNfUFlfQzQ=", name: "NPY", number: 4, keyId: "OGY2NmZlMTU3MzViMmIxYjNkNWViMzY0NmNhYTQwNWU=", key: "NDA0YjkzZmQ3YjQ5OWIxMDYxYzlhNzE0ZTFjZGIyZDA=" },
    "la-tele": { id: "TEFfVEVMRV9DNA==", name: "La Tele", number: 4, keyId: "N2M2YTQ4MWFkZjZhMDgwZWMwOTYzN2QzZjI1OTg5Y2Y=", key: "MDM2ZTM0M2Q2MzZiODIxYWI4MTgzOGRlMzg3YjYyY2I=" },
    "sur-tv": { id: "U1VSX1RWX0M0", name: "Sur TV", number: 4, keyId: "YzA0Nzc2NGE5MGU5YTViMDIxM2FlYzhmZWQ4YTI0YWE=", key: "MDdlNjIwMDEwNjRmYmU2NDc5NmI0ZWQzODM2NzYxZjQ=" },
    "teledoce": { id: "Q2FuYWwxMlVSVQ==", name: "Teledoce", number: 4, keyId: "ZGZkZTlkMzVkNzQzOGJmZGY2MWRhNWRmYWMwNTU3YzE=", key: "YWNiMTMzNzBjMDNhNzI1NGUyYmI5Y2M5ZDIxMjUwMTc=" },
    "canal-4-uy": { id: "Q2FuYWw0X1VSVQ==", name: "Canal 4 (Uruguay)", number: 4, keyId: "ZGFiZWZhYWM4OTc0MjU4OTc3OGZjZmFiNzhmMDgzNTQ=", key: "ODk2ZGQ5MTQ2ODNiMDFjODA0NGZmZDM0ZDdiNjQxNmI=" },
    "hbo-hd": { id: "SEJPSEQ=", name: "HBO", number: 4, keyId: "NTMxNzI4M2Y0MTEwZmFjM2ZiM2EwYmVjZDlmNjQ4YmM=", key: "MDc1NGEwM2M5MjZiMTI0NzIxNmUwMWQ5ZGJjZmFjMjg=" },
    "canal-10-uy": { id: "Q2FuYWwxMF9VUlU=", name: "Canal 10 (Uruguay)", number: 4, keyId: "OGRkMzQ3ODJkNzU0ZjhmY2IxZThiMzhkYTlmZmFkMGI=", key: "NmZiOTc0NjdjMGYwZWExM2Y4NmQ0MWE3MGUwMjljNTE=" },
    "rpc": { id: "UlBDX0M0", name: "RPC", number: 4, keyId: "YTgwOTNjZGNiMmQ1MDRiZDM4ZjE2NzY0YmQyMWI2ZTU=", key: "YmZjZjNiMDMzYjVmMGI1YWUwMjA3NTFhNjc0NjMyNmY=" },
    "espn2-uy": { id: "RVNQTjJfVVk=", name: "ESPN 2 (UY)", number: 4, keyId: "MGQ4MjAxMDAxNDQ3NzJmZWQ5ZjM4YjgzNjUwZmE3ZTE=", key: "ZGVkOGNjNDdiMjliMGViMGIwYTg3ZGYyMmU3MjE4NDc=" },
    "espn-uy": { id: "RVNQTl9VWQ==", name: "ESPN (UY)", number: 4, keyId: "NjM2MmUxZjM2ZmNiN2VlM2M0N2RlYmQ5MTQwMzM2YWQ=", key: "OWJhMWQ0NmM1YjljN2EzMTMwYTVkYWJiZjcxNTUxNzU=" }
};
